inbound-transport:
  - [http, 0.0.0.0, 3000]
label: Alice
outbound-transport: http
endpoint: http://alice:3000
admin: [0.0.0.0, 3001]
admin-insecure-mode: true
log-level: debug
genesis-url: https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
wallet-type: indy
wallet-name: alice
wallet-key: insecure
auto-provision: true
tails-server-base-url: http://tails:6543
